#Local MongoDB config
#spring.data.mongodb.authentication-database=
#spring.data.mongodb.username=
#spring.data.mongodb.password=
#spring.data.mongodb.database: test123
#spring.data.mongodb.port: 27017
#spring.data.mongodb.host: localhost

spring:
  application:
    name: BootMongo
  data:
    mongodb:
      database: test123
      port: 27017
      host: localhost


# App config
#server.port: 8102
server:
  port: 8102
  context-path: /user
  display-name: SnapIntegration
#spring.application.name: BootMongo
#server.display-name: SnapIntegration
#server.context-path: /user
